/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JADE_exemple_personnel;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import javax.swing.JPanel;

/**
 *
 * @author Francois
 */
public class mainWindow extends javax.swing.JFrame {

    private final int taillePixel = 5;
    private Graphics g2d;
    private int grille[][];
    private JPanel panels[][];
    /**
     * Creates new form mainWindow
     */
    public mainWindow() {
        initComponents();
        
        GenerateurGrille newgrille = new GenerateurGrille(9, -9, 100, 50, 3);
        grille = newgrille.generer();
        
        jPanel1.setLayout(new GridLayout(50,100));
        panels = new JPanel[50][100];
        for(int j=0; j<grille.length; j++){
            for(int i=0; i<grille[j].length; i++){
               panels[j][i] = new JPanel();
               drawCase(i,j, grille[j][i]);
               panels[j][i].setPreferredSize(new Dimension(taillePixel, taillePixel));
               jPanel1.add(panels[j][i]);
            }
        }
        
        // Affichage grille test
        for(int j=0; j<grille.length; j++){
            for(int i=0; i<grille[j].length; i++){
                if(grille[j][i] >=0)
                    System.out.print("+");
                System.out.print(grille[j][i] + " ");
            }
            System.out.println();
        }   
        
    }
    
    
    private void drawCase(int i, int j, int temp){
        switch (temp) {
            case 10:
                panels[j][i].setBackground(new Color(196,10,12));
                break;
            case 9:
                panels[j][i].setBackground(new Color(204,30,28));
                break;
            case 8:
                panels[j][i].setBackground(new Color(204,46,44));
                break;
            case 7:
                panels[j][i].setBackground(new Color(212,74,76));
                break;   
            case 6:
                panels[j][i].setBackground(new Color(220,94,92));
                break;
            case 5:
                panels[j][i].setBackground(new Color(244,122,124));
                break;   
            case 4:
                panels[j][i].setBackground(new Color(236,138,140));
                break; 
            case 3:
                panels[j][i].setBackground(new Color(244,158,156));
                break; 
            case 2:
                panels[j][i].setBackground(new Color(244,178,180));
                break;    
            case 1:
                panels[j][i].setBackground(new Color(252,202,204));
                break;          
            case -10:
                panels[j][i].setBackground(new Color(12,10,196));
                break;
            case -9:
                panels[j][i].setBackground(new Color(36,34,204));
                break;
            case -8:
                panels[j][i].setBackground(new Color(52,54,212));
                break;
            case -7:
                panels[j][i].setBackground(new Color(68,70,212));
                break;   
            case -6:
                panels[j][i].setBackground(new Color(92,94,220));
                break;
            case -5:
                panels[j][i].setBackground(new Color(108,110,220));
                break;   
            case -4:
                panels[j][i].setBackground(new Color(140,142,244));
                break; 
            case -3:
                panels[j][i].setBackground(new Color(156,158,236));
                break; 
            case -2:
                panels[j][i].setBackground(new Color(180,182,244));
                break;    
            case -1:
                panels[j][i].setBackground(new Color(204,202,252));
                break;    
            case 0:
                panels[j][i].setBackground(new Color(252,202,204));
                break; 
            default:
                panels[j][i].setBackground(new Color(254,254,254));
                break;
        }        
    }
    
    
    public void draw(){
    jPanel1.repaint();
    
        for(int i=0; i<grille.length; i++){
            for(int j=0; j<grille[0].length; j++){
                if(this.grille[i][j] != 1000){
                    //g2d.drawOval(i*taillePixel, j*taillePixel, taillePixel, taillePixel);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton1.setText("Ajouter un agent capteur");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
