package JADE_exemple_personnel;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;

public class mainWindow extends javax.swing.JFrame {

    MainAgent agent;
    private final int taillePixel = 5;
    private int grille[][];
    private CasePanel panels[][];
    /**
     * Creates new form mainWindow
     * @param mainagent main agent
     */
    public mainWindow(MainAgent mainagent) {     
        agent = mainagent;
        initComponents();
        this.setResizable(false);
        this.setTitle("Demo Jade");
        
        GenerateurGrille newgrille = new GenerateurGrille(9, -9, 100, 50, 3);
        grille = newgrille.generer();
        
        jPanel1.setLayout(new GridLayout(50,100));
        panels = new CasePanel[50][100];
        for(int j=0; j<grille.length; j++){
            for(int i=0; i<grille[j].length; i++){
               panels[j][i] = new CasePanel(i,j);
               panels[j][i].addMouseListener(new MouseAdapter(){
                    @Override
                    public void mousePressed(MouseEvent e) {
                        CasePanel caseP = (CasePanel)e.getSource();
                        agent.createCapteurAgent(caseP.getXPos(), caseP.getYPos());
                    }
               });
               drawCase(i,j, 100);
               panels[j][i].setPreferredSize(new Dimension(taillePixel, taillePixel));
               jPanel1.add(panels[j][i]);
            }
        } 
    }
    
    public void drawGrille(){
        for(int j=0; j<grille.length; j++){
            for(int i=0; i<grille[j].length; i++){    
                if(agent.casesVisibles[j][i])
                   drawCase(i, j, grille[j][i]); 
            }
        }
    }
    
    public void drawCase(int i, int j, int temp){
        switch (temp) {
            case 10:
                panels[j][i].setBackground(new Color(196,10,12));
                break;
            case 9:
                panels[j][i].setBackground(new Color(204,30,28));
                break;
            case 8:
                panels[j][i].setBackground(new Color(204,46,44));
                break;
            case 7:
                panels[j][i].setBackground(new Color(212,74,76));
                break;   
            case 6:
                panels[j][i].setBackground(new Color(220,94,92));
                break;
            case 5:
                panels[j][i].setBackground(new Color(244,122,124));
                break;   
            case 4:
                panels[j][i].setBackground(new Color(236,138,140));
                break; 
            case 3:
                panels[j][i].setBackground(new Color(244,158,156));
                break; 
            case 2:
                panels[j][i].setBackground(new Color(244,178,180));
                break;    
            case 1:
                panels[j][i].setBackground(new Color(252,202,204));
                break;          
            case -10:
                panels[j][i].setBackground(new Color(12,10,196));
                break;
            case -9:
                panels[j][i].setBackground(new Color(36,34,204));
                break;
            case -8:
                panels[j][i].setBackground(new Color(52,54,212));
                break;
            case -7:
                panels[j][i].setBackground(new Color(68,70,212));
                break;   
            case -6:
                panels[j][i].setBackground(new Color(92,94,220));
                break;
            case -5:
                panels[j][i].setBackground(new Color(108,110,220));
                break;   
            case -4:
                panels[j][i].setBackground(new Color(140,142,244));
                break; 
            case -3:
                panels[j][i].setBackground(new Color(156,158,236));
                break; 
            case -2:
                panels[j][i].setBackground(new Color(180,182,244));
                break;    
            case -1:
                panels[j][i].setBackground(new Color(204,202,252));
                break;    
            case 0:
                panels[j][i].setBackground(new Color(252,202,204));
                break; 
            case 50:
                panels[j][i].setBackground(new Color(34,120,15));
                break;
            default:
                panels[j][i].setBackground(new Color(48,48,48));
                break;
        }        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = jList1 = new JList<String>(new DefaultListModel<String>());
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jList1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setText("Liste des agents capteurs :");

        jLabel2.setText("Carte des températures mis à jour par l'agent principal :");

        jLabel3.setText("Logs des créations d'agents et des communications :");

        jLabel4.setText("Cliquez sur une case pour ajouter un agent capteur !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the grille
     */
    public int[][] getGrille() {
        return grille;
    }

    /**
     * @return the jList1
     */
    public javax.swing.JList<String> getjList1() {
        return jList1;
    }

    /**
     * @return the jTextArea1
     */
    public javax.swing.JTextArea getjTextArea1() {
        return jTextArea1;
    }

}
